# Generated by Django 5.0.7 on 2024-08-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
    ]
