# Generated by Django 5.0.7 on 2024-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_persona_demographics_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketanalysis',
            name='competitor_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='competitor_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='competitor_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='competitor_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='competitor_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='market_growth_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='market_growth_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='market_growth_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='market_growth_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='market_growth_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='market_segmentation_female',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='market_segmentation_male',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='market_size_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='market_size_value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
