# Generated by Django 5.0.7 on 2024-08-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_marketanalysis_competitor_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='demographics_gender',
            field=models.CharField(default='male', max_length=255),
        ),
    ]
