# Generated by Django 5.0.7 on 2024-08-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_marketanalysis_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='demographics_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='demographics_gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='demographics_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='demographics_occupation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='demographics_salary',
            field=models.FloatField(null=True),
        ),
    ]
