# Generated by Django 5.0.7 on 2024-08-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
