# Generated by Django 5.0.7 on 2024-08-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupproject',
            name='generated_idea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupproject',
            name='generated_market_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupproject',
            name='generated_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupproject',
            name='generated_slogan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupproject',
            name='generated_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupproject',
            name='generated_user_persona',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupproject',
            name='startup_idea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupproject',
            name='target_date_goal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupproject',
            name='target_number_of_users_goal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
