# Generated by Django 5.0.7 on 2024-08-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup_project', '0002_alter_startupproject_generated_idea_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartupProject',
        ),
    ]
